### ISSUE TITLE
Description for install raspbee2 missing a reboot

### ISSUE THREAD

**Issue by mmarras** [dresden-elektronik/raspbee2-rtc#1]
Hi,
I had the problem that running `sudo make install` pointed to a an old `lib/modules/` version because it was updated during the upgrade. A reboot was required before `uname -r` would spit out the newly installed version. Maybe for generality good to include another reboot after step 1 of the install procedure.

**Comment by ChrisHae** [comment]
Description updated. Also a sudo apt upgrade is recommended first.
