### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by padzster** [dresden-elektronik/raspbee2-rtc#11]
Hi

I'm running Homebridge on Raspberry Pi 4 Model B. I've bought the RaspBee II and installed as instructed here https://github.com/homebridge/homebridge-raspbian-image/wiki/How-To-Install-deCONZ-for-ConBee-or-RaspBee

However, when I get to entering these two lines:

sudo hwclock --systohc
sudo hwclock --verbose

I get the following:

sudo hwclock --systohc
hwclock: Cannot access the Hardware Clock via any known method.
hwclock: Use the --verbose option to see the details of our search for an access method.

sudo hwclock --verbose
hwclock from util-linux 2.33.1
System Time: 1607942858.226220
Trying to open: /dev/rtc0
Trying to open: /dev/rtc
Trying to open: /dev/misc/rtc
No usable clock interface found.
hwclock: Cannot access the Hardware Clock via any known method.

Could anyone help please?

**Comment by ChrisHae** [comment]
Hi, can you first try these installation steps: https://phoscon.de/en/raspbee2/install#raspbian

**Comment by padzster** [comment]
Hi. Sorry for the delay. Just wanted to check: will this be compatible with Homebridge that is currently installed on the Pi?

**Comment by ChrisHae** [comment]
Yes, just the RTC-Installation. It is independent of Homebridge.

**Comment by padzster** [comment]
Hi.
I ran the code but hit an error:

pi@homebridge:/var/lib/homebridge $  cd raspbee2-rtc-master
pi@homebridge:/var/lib/homebridge/raspbee2-rtc-master $ make
checking deb package dependencies...
i2c-tools
build-essential
raspberrypi-kernel-headers
build rtc module...
make -C /lib/modules/5.4.51-v7l+/build M=/var/lib/homebridge/raspbee2-rtc-master modules
make[1]: *** /lib/modules/5.4.51-v7l+/build: No such file or directory.  Stop.
make: *** [Makefile:17: build] Error 2
pi@homebridge:/var/lib/homebridge/raspbee2-rtc-master $  sudo make install
install rtc module...
make[1]: *** /lib/modules/5.4.51-v7l+/build: No such file or directory.  Stop.
could not install rtc module file (did you run make?)
make: *** [Makefile:42: install] Error 1

what should i do?

**Comment by ChrisHae** [comment]
You need to update the kernel to the stable version 5.4.83. 
Or you use https://github.com/RPi-Distro/rpi-source to install the kernel headers for your kernel.

**Comment by padzster** [comment]
Sorry not sure what to do to update the kernel

**Comment by ChrisHae** [comment]
For me: doing sudo apt update then sudo apt upgrade and then reboot was enough.
I had Kernel version 5.4.72 before and 5.4.83 afterwards.

**Comment by padzster** [comment]
Did all that and it still says 5.4.51-v7l+

**Comment by ChrisHae** [comment]
Then try rpi-source https://github.com/RPi-Distro/rpi-source
Just follow the 3 steps: Dependencies, Install and Run.
It does not upgrade youe kernel but it should install the build directory.
Then just repeat the make and make install steps from the rtc installation.
