### ISSUE TITLE
Compiler Error RTC_VL_DATA_INVALID

### ISSUE THREAD

**Issue by ksdehoff** [dresden-elektronik/raspbee2-rtc#12]
Hello:  Just trying to get this installed and run into an issue during the compile:
/home/pi/raspbee2-rtc-master/rtc-pcf85063.c:300:42: error: ‘RTC_VL_DATA_INVALID’ undeclared (first use in this function); did you mean ‘PM_EVENT_INVALID’?
   status = status & PCF85063_REG_SC_OS ? RTC_VL_DATA_INVALID : 0;
                                          ^~~~~~~~~~~~~~~~~~~
                                          PM_EVENT_INVALID

Hoping you can have a look at the compile flags or the code.  This is on the latest (12/26/20) buster build - confusing kernel status - uname -r=5.10.2-v7+ but there was no build directory for that kernel so I overrode it with 5.4.79-v7+ in the makefile

**Comment by ChrisHae** [comment]
I think it is because of the changes you made manually. The correct way would be update the kernel then 
 sudo apt update
 sudo apt upgrade
 reboot
before proceeding with the install.

**Comment by ksdehoff** [comment]
The changes were made manually due to this error - why fix something that's not broke
