### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Sashik259** [dresden-elektronik/raspbee2-rtc#13]
Hello!
I’ve just bought and installed Raspbee II in my Raspberri Pi 4 8Gb, Raspbian OS desktop version.
I tried to install RTC as written in readme file
But when I started ‘make’ command (step 4) I got error:

> make[1]: *** /lib/modules/5.10.6-v7l+/build: No such file or directory.  Stop

I’ve manually created this directory and then run ‘make’ command again but got another error:

> make[1]: *** No rule to make target 'modules'.  Stop.
> make[1]: Leaving directory '/usr/lib/modules/5.10.6-v7l+/build'
> make: *** [Makefile:17: build] Error 2

I have read [here](https://github.com/dresden-elektronik/raspbee2-rtc/issues/2) - but it doesn't solve my problem
What should I do?
Please help!

**Comment by ChrisHae** [comment]
Have you already solved your problem? Else I would recommend do

> sudo apt update
> sudo apt upgrade
> reboot

first.

**Comment by Sashik259** [comment]
> Have you already solved your problem? Else I would recommend do
> 
> > sudo apt update
> > sudo apt upgrade
> > reboot
> 
> first.

Thank you for fast reply. I just did it. Then run 'make' again and got following message:

> checking deb package dependencies...
> i2c-tools
> build-essential
> raspberrypi-kernel-headers
> build rtc module...
> make -C /lib/modules/5.10.6-v7l+/build M=/home/pi/raspbee2-rtc-master modules
> make[1]: Entering directory '/usr/lib/modules/5.10.6-v7l+/build'
> make[1]: *** No rule to make target 'modules'.  Stop.
> make[1]: Leaving directory '/usr/lib/modules/5.10.6-v7l+/build'
> make: *** [Makefile:17: build] Error 2

**Comment by ChrisHae** [comment]
What is the output of uname -r ?

**Comment by Sashik259** [comment]
5.10.6-v7l+

**Comment by risdevs** [comment]
same issue here, with newest kernel 

```
pi@home:~/raspbee2-rtc-master $ uname -r
5.10.7-v7l+

pi@home:~/raspbee2-rtc-master $ make
checking deb package dependencies...
i2c-tools
build-essential
raspberrypi-kernel-headers
build rtc module...
make -C /lib/modules/5.10.7-v7l+/build M=/home/pi/raspbee2-rtc-master modules
make[1]: *** /lib/modules/5.10.7-v7l+/build: No such file or directory.  Stop.
make: *** [Makefile:17: build] Error 2
```

**Comment by ChrisHae** [comment]
You have to install the raspberry pi kernel headers to get the build directory and to build kernel modules. Creating a build directory yourself has no effect. For new Kernel releases it can take a few weeks until the repository is updated: https://www.raspberrypi.org/documentation/linux/kernel/headers.md
The documentation suggests to clone the kernel as described in their Build Section. Alternatively you can downgrade to the latest stable kernel (5.4.83).

**Comment by mrclschstr** [comment]
This might ease up some steps: https://github.com/RPi-Distro/rpi-source

**Comment by Sashik259** [comment]
Thank you so much!
I've reinstalled 5.4.83-v7l+
RTC works, but it gives an error:

> USER@raspberrypi:~ $ sudo hwclock --verbose
> [sudo] password for USER: 
> hwclock from util-linux 2.33.1
> System Time: 1611395292.300711
> Trying to open: /dev/rtc0
> Using the rtc interface to the clock.
> Last drift adjustment done at 1611392630 seconds after 1969
> Last calibration done at 1611392630 seconds after 1969
> Hardware clock is on UTC time
> Assuming hardware clock is kept in UTC time.
> Waiting for clock tick...
> **ioctl(4, RTC_UIE_ON, 0): Invalid argument**
> Waiting in loop for time from /dev/rtc0 to change
> ...got clock tick
> Time read from Hardware Clock: 2021/01/23 09:48:14
> Hw clock time : 2021/01/23 09:48:14 = 1611395294 seconds since 1969
> Time since last adjustment is 2664 seconds
> Calculated Hardware Clock drift is 0.000000 seconds
> 2021-01-23 12:48:13.286949+03:00

Is it critical?

**Comment by mrclschstr** [comment]
I have the same error and others too (see #10). I don't think it's critical but I cannot say for sure; at least everything is working ;-)
