### ISSUE TITLE
makefile error

### ISSUE THREAD

**Issue by FSorrow** [dresden-elektronik/raspbee2-rtc#2]
Hi everybody, I'm trying installing RTC in my pi4 running hoobs but i'm stuck here:

hoobs@hoobs:/home/hoobs/.hoobs/etc $ cd raspbee2-rtc-master
hoobs@hoobs:/home/hoobs/.hoobs/etc/raspbee2-rtc-master $ make
checking deb package dependencies...
i2c-tools
build-essential
raspberrypi-kernel-headers
build rtc module...
make -C /lib/modules/4.19.97-v8+/build M=/home/hoobs/.hoobs/etc/raspbee2-rtc-master modules
make[1]: *** /lib/modules/4.19.97-v8+/build: No such file or directory.  Stop.
make: *** [Makefile:17: build] Error 2

what can i do ? Thank you

**Comment by Kienz** [comment]
Have the same issue on rpi4

**Comment by ChrisHae** [comment]
Hi,

the system can't find the build directory for that kernel version. That means you should do a 
sudo apt update, sudo apt upgrade and then reboot. Then you should try make again.

The upgrade step was not in the install instructions but it is necessary and was added recently.

**Comment by ChrisHae** [comment]
P.S. after installing the RTC please make sure that deCONZ is running when testing the RTC. There is currently a problem with the firmware that affects the RTC when deCONZ is not running.

**Comment by FSorrow** [comment]
Thanks, after lots of tests (tried many times sudo apt update, sudo apt upgrade and nothing change for me)So, if this could help anyone I made this:
- install Homebridge-hue + Raspbian Buster image from phoscon
- upgrade HomeBridge to hoobs
- changing deconz ports

That was the only way that I found to solve my issue (RTC was for a raspbee II)

**Comment by glefand** [comment]
Hi,
I got the same issue, I'm using a homebridge.io image, all updated

uname -a
Linux homebridge 5.4.42-v7l+ #1319 SMP Wed May 20 14:12:03 BST 2020 armv7l GNU/Linux

the thing is there is no header files for this kernel
pi@homebridge:~ $ cd /usr/src
pi@homebridge:/usr/src $ ls
linux-headers-4.19.118+  linux-headers-4.19.118-v7+  linux-headers-4.19.118-v7l+

and I don't know how to install them

**Comment by ChrisHae** [comment]
I have checked the download link for this kernel and it worked. https://raw.githubusercontent.com/torvalds/linux/5.4.42/drivers/rtc/rtc-pcf85063.c
So the makefile should also work. If not you could download the file manually with that link.

**Comment by ChrisHae** [comment]
It looks the kernel version is very new. You could use rpi-source https://github.com/notro/rpi-source/wiki to download it.

**Comment by Wreorbriens** [comment]
Hey there,

unfortunately I got a error message today that is quite the same:

xxx@xxx:~/raspbee2-rtc-master $ make
checking deb package dependencies...
i2c-tools
build-essential
raspberrypi-kernel-headers
build rtc module...
make -C /lib/modules/5.4.70-v7l+/build M=/home/pi/raspbee2-rtc-master modules
make[1]: *** /lib/modules/5.4.70-v7l+/build: No such file or directory. Stop.
make: *** [Makefile:17: build] Error 2

The thing is: If I go to "*** /lib/modules/5.4.70-v7l+/" there is a folder named "build" but its the only one, which is a link-folder. When I open the link folder in a new window it's filled with files... May I ask you to help me in this case?

Thanks a lot in advance, community.

**Comment by ChrisHae** [comment]
It's strange because the build folder is present. Have you already tried sudo apt update, sudo apt upgrade and reboot?
What permissions does the build folder have?

**Comment by Wreorbriens** [comment]
Yes exactly, thought about if this maybe is because it's no "real" folder but a linked folder in there. To be honest I do not know how to check the permissions of a folder yet. If you would be so nice to explain me in general I would be thankful. Another thing is, that I've now installed the Buster image from Phoscon with the needed things pre-installed. Now I've only have to reinstall all the stuff again... 😅

Thanks a lot for fast feedback.

**Comment by ChrisHae** [comment]
You can check permissions with `ls -l` it lists all files and folders with permissions (the left column). You can also add a path behind it.
It is normal that the build folder is a symlink.
