### ISSUE TITLE
Cannot find any IKEA lights with Raspbee 2 installed

### ISSUE THREAD

**Issue by NiPoDd** [dresden-elektronik/raspbee2-rtc#6]
Hi, i'm new to this so have a little faith.
I have a just installed a Raspberry 4 with Home assistant in it and a Raspbee II with deconz(HA Plug-in).
I have set the config under "Device" and can find my gateway but no IKEA light's are found. Have tried the trick where you reset the  light and then search for light but nothing works, any ide?

The strange thing is that after i tried to re-install deConz and reset the gateway, the gateway page in Phoscon just disappeared.

**Comment by ChrisHae** [comment]
Hi, this GitHub repository is only for issues related to the RaspBeeII RTC. Questions related to deCONZ, lights and device issues go here: https://github.com/dresden-elektronik/deconz-rest-plugin/issues. You should also consider the Home Assistant Message Boards for Questions about the HA deCONZ Plugin.

To speak from my experience, IKEA lights work well with deCONZ and RaspBeeII but sometimes they it can take a little bit longer to make them join the network. You have to reset them (6x off/on with the FW version that my lamps have) and then they start blinking. You should start the light search in the phosocon app now or before you reset the lights. Then you might need to switch them off/on one more time.

And of course check if deCONZ and the RaspBeeII operate as intended. Have you already connected other lights/devices and are they controlable? Or check the Settings/Gateway page of the phoscon app. It should show the FW version of the RaspBeeII and should **not** show "Not connected".
